### PR TITLE
Develop

### LINKED ISSUE #1: Use OpenZeppelin
Use OpenZeppelin for ERC20 and SafeMath for safe operations (their contracts are already audited)

### PR DESCRIPTION
**Pull request by vdrg**
* Removed EIP20 and EIP621
* Use zeppelin contracts from node_modules (standard token, DetailedERC20, SafeMath, etc)
* Create a cCLP contract (it has the parameters hardcoded, instead of setting them in the migrations)

Fixes #1 and #2

### CODE REVIEW

**Comment by ajunge** [comment]
Ok. Thanx for the great work. Since is already merged to develop I will just close this PR

**Comment by vdrg** [comment]
Hi! this PR is merging develop into master so I will reopen it (unless you think it is better to wait until the tests are done before merging to master)

**Comment by ajunge** [comment]
We are using git flow, so all "feature" branches or PRs like this one should merge to develop only. The only type of branches that merge into master are the "release" and "hotfix" branches. Closing again

**Comment by vdrg** [comment]
Perfect, thanks :smiley:

**Pull request closed without merging**
